
import { Department, ClimateZone } from './types';

export const DEPARTMENTS: Department[] = [
  { code: '01', name: 'Ain', zone: ClimateZone.H1 },
  { code: '02', name: 'Aisne', zone: ClimateZone.H1 },
  { code: '03', name: 'Allier', zone: ClimateZone.H1 },
  { code: '04', name: 'Alpes-de-Haute-Provence', zone: ClimateZone.H2 },
  { code: '05', name: 'Hautes-Alpes', zone: ClimateZone.H1 },
  { code: '06', name: 'Alpes-Maritimes', zone: ClimateZone.H3 },
  { code: '07', name: 'Ardèche', zone: ClimateZone.H1 },
  { code: '08', name: 'Ardennes', zone: ClimateZone.H1 },
  { code: '09', name: 'Ariège', zone: ClimateZone.H2 },
  { code: '10', name: 'Aube', zone: ClimateZone.H1 },
  { code: '11', name: 'Aude', zone: ClimateZone.H2 },
  { code: '12', name: 'Aveyron', zone: ClimateZone.H2 },
  { code: '13', name: 'Bouches-du-Rhône', zone: ClimateZone.H3 },
  { code: '14', name: 'Calvados', zone: ClimateZone.H1 },
  { code: '15', name: 'Cantal', zone: ClimateZone.H1 },
  { code: '16', name: 'Charente', zone: ClimateZone.H2 },
  { code: '17', name: 'Charente-Maritime', zone: ClimateZone.H2 },
  { code: '18', name: 'Cher', zone: ClimateZone.H2 },
  { code: '19', name: 'Corrèze', zone: ClimateZone.H1 },
  { code: '2A', name: 'Corse-du-Sud', zone: ClimateZone.H3 },
  { code: '2B', name: 'Haute-Corse', zone: ClimateZone.H3 },
  { code: '21', name: 'Côte-d\'Or', zone: ClimateZone.H1 },
  { code: '22', name: 'Côtes-d\'Armor', zone: ClimateZone.H2 },
  { code: '23', name: 'Creuse', zone: ClimateZone.H1 },
  { code: '24', name: 'Dordogne', zone: ClimateZone.H2 },
  { code: '25', name: 'Doubs', zone: ClimateZone.H1 },
  { code: '26', name: 'Drôme', zone: ClimateZone.H1 },
  { code: '27', name: 'Eure', zone: ClimateZone.H1 },
  { code: '28', name: 'Eure-et-Loir', zone: ClimateZone.H1 },
  { code: '29', name: 'Finistère', zone: ClimateZone.H2 },
  { code: '30', name: 'Gard', zone: ClimateZone.H3 },
  { code: '31', name: 'Haute-Garonne', zone: ClimateZone.H2 },
  { code: '32', name: 'Gers', zone: ClimateZone.H2 },
  { code: '33', name: 'Gironde', zone: ClimateZone.H2 },
  { code: '34', name: 'Hérault', zone: ClimateZone.H3 },
  { code: '35', name: 'Ille-et-Vilaine', zone: ClimateZone.H2 },
  { code: '36', name: 'Indre', zone: ClimateZone.H2 },
  { code: '37', name: 'Indre-et-Loire', zone: ClimateZone.H2 },
  { code: '38', name: 'Isère', zone: ClimateZone.H1 },
  { code: '39', name: 'Jura', zone: ClimateZone.H1 },
  { code: '40', name: 'Landes', zone: ClimateZone.H2 },
  { code: '41', name: 'Loir-et-Cher', zone: ClimateZone.H2 },
  { code: '42', name: 'Loire', zone: ClimateZone.H1 },
  { code: '43', name: 'Haute-Loire', zone: ClimateZone.H1 },
  { code: '44', name: 'Loire-Atlantique', zone: ClimateZone.H2 },
  { code: '45', name: 'Loiret', zone: ClimateZone.H1 },
  { code: '46', name: 'Lot', zone: ClimateZone.H2 },
  { code: '47', name: 'Lot-et-Garonne', zone: ClimateZone.H2 },
  { code: '48', name: 'Lozère', zone: ClimateZone.H2 },
  { code: '49', name: 'Maine-et-Loire', zone: ClimateZone.H2 },
  { code: '50', name: 'Manche', zone: ClimateZone.H2 },
  { code: '51', name: 'Marne', zone: ClimateZone.H1 },
  { code: '52', name: 'Haute-Marne', zone: ClimateZone.H1 },
  { code: '53', name: 'Mayenne', zone: ClimateZone.H2 },
  { code: '54', name: 'Meurthe-et-Moselle', zone: ClimateZone.H1 },
  { code: '55', name: 'Meuse', zone: ClimateZone.H1 },
  { code: '56', name: 'Morbihan', zone: ClimateZone.H2 },
  { code: '57', name: 'Moselle', zone: ClimateZone.H1 },
  { code: '58', name: 'Nièvre', zone: ClimateZone.H1 },
  { code: '59', name: 'Nord', zone: ClimateZone.H1 },
  { code: '60', name: 'Oise', zone: ClimateZone.H1 },
  { code: '61', name: 'Orne', zone: ClimateZone.H1 },
  { code: '62', name: 'Pas-de-Calais', zone: ClimateZone.H1 },
  { code: '63', name: 'Puy-de-Dôme', zone: ClimateZone.H1 },
  { code: '64', name: 'Pyrénées-Atlantiques', zone: ClimateZone.H2 },
  { code: '65', name: 'Hautes-Pyrénées', zone: ClimateZone.H2 },
  { code: '66', name: 'Pyrénées-Orientales', zone: ClimateZone.H3 },
  { code: '67', name: 'Bas-Rhin', zone: ClimateZone.H1 },
  { code: '68', name: 'Haut-Rhin', zone: ClimateZone.H1 },
  { code: '69', name: 'Rhône', zone: ClimateZone.H1 },
  { code: '70', name: 'Haute-Saône', zone: ClimateZone.H1 },
  { code: '71', name: 'Saône-et-Loire', zone: ClimateZone.H1 },
  { code: '72', name: 'Sarthe', zone: ClimateZone.H1 },
  { code: '73', name: 'Savoie', zone: ClimateZone.H1 },
  { code: '74', name: 'Haute-Savoie', zone: ClimateZone.H1 },
  { code: '75', name: 'Paris', zone: ClimateZone.H1 },
  { code: '76', name: 'Seine-Maritime', zone: ClimateZone.H1 },
  { code: '77', name: 'Seine-et-Marne', zone: ClimateZone.H1 },
  { code: '78', name: 'Yvelines', zone: ClimateZone.H1 },
  { code: '79', name: 'Deux-Sèvres', zone: ClimateZone.H2 },
  { code: '80', name: 'Somme', zone: ClimateZone.H1 },
  { code: '81', name: 'Tarn', zone: ClimateZone.H2 },
  { code: '82', name: 'Tarn-et-Garonne', zone: ClimateZone.H2 },
  { code: '83', name: 'Var', zone: ClimateZone.H3 },
  { code: '84', name: 'Vaucluse', zone: ClimateZone.H3 },
  { code: '85', name: 'Vendée', zone: ClimateZone.H2 },
  { code: '86', name: 'Vienne', zone: ClimateZone.H2 },
  { code: '87', name: 'Haute-Vienne', zone: ClimateZone.H2 },
  { code: '88', name: 'Vosges', zone: ClimateZone.H1 },
  { code: '89', name: 'Yonne', zone: ClimateZone.H1 },
  { code: '90', name: 'Territoire de Belfort', zone: ClimateZone.H1 },
  { code: '91', name: 'Essonne', zone: ClimateZone.H1 },
  { code: '92', name: 'Hauts-de-Seine', zone: ClimateZone.H1 },
  { code: '93', name: 'Seine-Saint-Denis', zone: ClimateZone.H1 },
  { code: '94', name: 'Val-de-Marne', zone: ClimateZone.H1 },
  { code: '95', name: 'Val-d\'Oise', zone: ClimateZone.H1 },
  { code: '971', name: 'Guadeloupe', zone: ClimateZone.H3 },
  { code: '972', name: 'Martinique', zone: ClimateZone.H3 },
  { code: '973', name: 'Guyane', zone: ClimateZone.H3 },
  { code: '974', name: 'La Réunion', zone: ClimateZone.H3 },
  { code: '976', name: 'Mayotte', zone: ClimateZone.H3 },
];

export const getZoneByCode = (code: string): ClimateZone => {
  const dept = DEPARTMENTS.find(d => d.code === code);
  return dept ? dept.zone : ClimateZone.H1; 
};

export const ENERGY_PRICES = {
  OIL_LITER: 1.25, 
  OIL_KWH_PER_LITER: 10.0,
  OIL_EFFICIENCY: 0.82, 
  OIL_CO2_PER_LITER: 3.0,

  GAZ_KWH: 0.12, 
  GAZ_EFFICIENCY: 0.88,
  GAZ_CO2_PER_KWH: 0.23,

  ELEC_KWH: 0.25, 
  CO2_ELEC: 0.05, 
};

export const PAC_SPECS = {
  [ClimateZone.H1]: { SCOP: 3.2 },
  [ClimateZone.H2]: { SCOP: 3.8 },
  [ClimateZone.H3]: { SCOP: 4.5 },
};
